# Generated by Django 4.0.2 on 2022-03-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
    ]
