# Generated by Django 4.0.2 on 2022-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_message_content_messagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontent',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
