# Generated by Django 4.0.2 on 2022-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_messagecontent_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontent',
            name='from_user',
            field=models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], default='sender', max_length=10),
        ),
    ]
